### DISCUSSION TITLE
Nap Time Automation

### DISCUSSION THREAD

**Discussion by marechel88** [cdnninja/yoto_ha#180] [Ideas]
Subject: Question About Automating Morning Time Adjustments for Nap Time

Hi there! First off, thank you for all the work on this integration — it’s been amazing to bring Yoto into Home Assistant!

We use our Yoto players every day with Morning and Night modes, and they've been an essential part of our family’s routine. I’m hoping to expand on this a bit for our daily nap times.

Currently, when our kids go down for a nap (around 12:00 PM to 3:00 PM), we manually push the morning time back to match nap wake-up (setting it to 3:00 PM). That way, when nap ends, the player’s morning color is active, and it signals to them that it's time to leave their room. After nap, we then manually reset the morning time back to the normal 7:00 AM for the next day.

In trying to automate this, I didn’t see a service exposed yet that would allow setting the Morning Time (or Night Time) values directly.
If it were available, it would open up some great automation possibilities — like triggering a toggle or automation to:

Adjust Morning Time to 3:00 PM at nap start

Reset Morning Time to 7:00 AM after nap ends

Would it be possible to expose a service to set Morning Time (and maybe Night Time too) dynamically?
Or if I’m missing an existing method, I’d love some guidance on how to approach it!

Thanks again for all your work — it’s been a game-changer for our family!

**Comment by cdnninja** [comment]
I think it exists today.  Here is a screenshot showing the time can be edited.  I would need to check the service call for automation but should be the native ha one.  

![image](https://github.com/user-attachments/assets/e620dc75-b71d-42af-adac-61f378a5647a)

**Comment by marechel88** [comment]
Thanks so much for the quick reply!
I'm still pretty new to working with YAML, and I couldn't find the service easily under the usual automation "device action" options at first. (I believe I'm confusing my terminology here but hopefully you get what I'm saying).

I also figured out (with a little help from ChatGPT - and you) that changing the morning and night time values needs to happen through basic Home Assistant services — not a unique Yoto HACS service.
Using time.set_value on the time entity did the trick!

Appreciate you pointing me in the right direction — it helped a ton! See my example below for the YAML automations to change the morning time via YAML. Hopefully this will help assist other in the search of a Nap Time use. I wish this was baked into the YOTO OS but I'll take this for sure. Love HA.

For other users, the only thing you'll need to change is the Yoto device name. Noted with comment below.

**"Turn On Nap Time"**
```
alias: Nap Time ON - Set Yoto Morning Time
trigger:
  - platform: state
    entity_id: input_boolean.nap_time
    to: 'on'
action:
  - service: time.set_value
    data:
      entity_id: time.z_owen_old_gen_2_day_mode #"z_owen_old_gen_2" is the name of my test Yoto Gen 2
      time: '15:00:00'
mode: single
```

**"Turn Off Nap Time"**
```
alias: Nap Time OFF - Reset Yoto Morning Time
trigger:
  - platform: state
    entity_id: input_boolean.nap_time
    to: 'off'
action:
  - service: time.set_value
    data:
      entity_id: time.z_owen_old_gen_2_day_mode #"z_owen_old_gen_2" is the name of my test Yoto Gen 2
      time: '06:30:00'
mode: single
```
